- name: Deinstall old Oracle Database Software and remove old oracle database home
  hosts: all
  vars:
    old_db_home: /u01/app/oracle/product/19.24/dbhome_1
    patch_dir: /u01/app/Setup
    ansible_python_interpreter: /usr/bin/python3
    removed_value: REMOVED="T"/>
  remote_user: root

  tasks:
    - name: Deinstall old_dbhome
      become: yes
      become_user: oracle
      become_method: su
      ansible.builtin.expect:
        command: /bin/bash -c {{ old_db_home }}/deinstall/deinstall
        responses:
          'Do you want to continue': 'y'
          'Specify the list of database names': ''
        echo: yes
        timeout: 600
      run_once: true
      register: deinstall_result

    - name: Check inventory whether old_dbhome is tagged with removed flag
      ansible.builtin.shell:
        cmd: "grep '{{ old_db_home }}' /u01/app/oraInventory/ContentsXML/inventory.xml | awk '{ print $NF }'"
      register: removedflag

    - name: Remove parent directory of old_db_home
      ansible.builtin.file:
        path: "{{ old_db_home | dirname }}"
        state: absent
      environment:
        OLDDBHOME: "{{ old_db_home }}"
      when: deinstall_result.rc == 0 or removedflag.stdout == removed_value
